import type { Listing, Product, Seller } from "./types";

/**
 * Demo data. Photos are club photos used as placeholders until real item
 * photos exist. Everything here is fictional.
 */

const sellers: Record<string, Seller> = {
  camille: { id: "u1", displayName: "Camille R.", memberSince: "2021-09-01", teams: ["cce"] },
  lucas: { id: "u2", displayName: "Lucas", memberSince: "2023-01-15", teams: ["pony-games"] },
  ines: { id: "u3", displayName: "Inès M.", memberSince: "2019-10-03", teams: ["dressage"] },
  theo: { id: "u4", displayName: "Théo", memberSince: "2024-03-20", teams: [] },
  margaux: { id: "u5", displayName: "Margaux L.", memberSince: "2020-05-11", teams: ["hunter"] },
  sophie: { id: "u6", displayName: "Sophie", memberSince: "2018-02-27", teams: ["equifun", "pony-games"] },
  nathan: { id: "u7", displayName: "Nathan B.", memberSince: "2022-11-08", teams: ["cce", "hunter"] },
  chloe: { id: "u8", displayName: "Chloé", memberSince: "2025-01-09", teams: [] },
};

const img = {
  a: "/offer_2.jpg",
  b: "/activity_1.jpg",
  c: "/activity_2.jpg",
  d: "/activity_3.jpg",
  e: "/activity_4.jpg",
  f: "/activity_5.jpg",
  g: "/carousel_1.jpeg",
  h: "/carousel_3.jpeg",
  i: "/carousel_4.jpeg",
  j: "/carousel_5.jpeg",
  k: "/carousel_6.jpeg",
  l: "/compet_1.jpg",
  m: "/compet_4.jpg",
  n: "/compet_5.jpg",
  o: "/compet_6.jpg",
  p: "/compet_7.jpg",
  q: "/compet_8.jpg",
  r: "/dressage.jpg",
  s: "/infr_1.jpg",
  t: "/infr_2.jpg",
  u: "/infr_3.jpg",
  v: "/slide_1.jpg",
  w: "/history.jpg",
  x: "/team.jpg",
};

export const LISTINGS: Listing[] = [
  {
    kind: "listing",
    id: "l1",
    slug: "casque-samshield-shadowmatt-m",
    title: "Casque Samshield Shadowmatt",
    categorySlug: "casques-protections",
    subCategorySlug: "casques",
    audience: "cavalier-adulte",
    size: "56 cm",
    brand: "Samshield",
    color: "noir",
    condition: "tres-bon-etat",
    price: 180,
    description:
      "Casque Samshield Shadowmatt taille M (56 cm), acheté en 2024. Porté une saison, aucune chute. Vendu avec sa housse d'origine et les mousses de réglage.\n\nAttention : un casque d'occasion doit être vérifié avant utilisation. Je peux le montrer au club.",
    images: [img.a, img.b],
    discipline: "cso",
    status: "publiee",
    publishedAt: "2026-09-08T10:12:00Z",
    seller: sellers.camille,
  },
  {
    kind: "listing",
    id: "l2",
    slug: "veste-concours-equipe-cce-bleu-marine",
    title: "Veste de concours Équipe CCE",
    categorySlug: "tenues-concours",
    subCategorySlug: "tenues-equipe",
    audience: "cavalier-adulte",
    size: "M",
    brand: "Equithème",
    color: "bleu-marine",
    condition: "bon-etat",
    price: 45,
    description:
      "Veste aux couleurs de l'équipe CCE du club, taille M. Je quitte l'équipe cette saison, elle attend un nouveau cavalier ! Quelques traces d'usage sur les poignets, rien de visible en piste.",
    images: [img.l, img.m],
    discipline: "cce",
    team: "cce",
    status: "publiee",
    publishedAt: "2026-09-07T18:40:00Z",
    seller: sellers.camille,
  },
  {
    kind: "listing",
    id: "l3",
    slug: "selle-mixte-wintec-500-17",
    title: "Selle mixte Wintec 500 17\" arcade réglable",
    categorySlug: "selles",
    subCategorySlug: "selles-mixtes",
    audience: "cheval",
    size: '17"',
    brand: "Wintec",
    color: "noir",
    condition: "bon-etat",
    price: 350,
    description:
      "Selle mixte synthétique Wintec 500, siège 17\", système d'arcade interchangeable (arcade medium montée, arcade wide fournie). Étriers et étrivières non inclus. Idéale pour débuter en concours ou pour un cheval de club.",
    images: [img.s, img.t, img.u],
    discipline: "cso",
    status: "publiee",
    publishedAt: "2026-09-06T09:00:00Z",
    seller: sellers.nathan,
  },
  {
    kind: "listing",
    id: "l4",
    slug: "bottes-ariat-heritage-contour-39",
    title: "Bottes Ariat Heritage Contour II",
    categorySlug: "chaussures-bottes",
    subCategorySlug: "bottes-equitation",
    audience: "cavalier-adulte",
    size: "39",
    brand: "Ariat",
    color: "noir",
    condition: "tres-bon-etat",
    price: 140,
    description:
      "Bottes en cuir Ariat, pointure 39, mollet medium, hauteur regular. Portées une dizaine de fois en concours. Vendues avec les embauchoirs.",
    images: [img.c, img.d],
    discipline: "hunter",
    status: "publiee",
    publishedAt: "2026-09-05T16:25:00Z",
    seller: sellers.margaux,
  },
  {
    kind: "listing",
    id: "l5",
    slug: "polo-equipe-pony-games-10-ans",
    title: "Polo Équipe Pony-Games enfant",
    categorySlug: "tenues-concours",
    subCategorySlug: "tenues-equipe",
    audience: "cavalier-enfant",
    size: "10 ans",
    brand: "HKM",
    color: "bleu",
    condition: "bon-etat",
    price: 12,
    description:
      "Polo officiel de l'équipe Pony-Games, taille 10 ans. Mon fils a grandi ! Logo brodé impeccable, quelques lavages.",
    images: [img.n],
    discipline: "pony-games",
    team: "pony-games",
    status: "publiee",
    publishedAt: "2026-09-05T08:10:00Z",
    seller: sellers.sophie,
  },
  {
    kind: "listing",
    id: "l6",
    slug: "tapis-dressage-eskadron-full-blanc",
    title: "Tapis de dressage Eskadron Cotton Full",
    categorySlug: "tapis-pads",
    subCategorySlug: "tapis-selle",
    audience: "cheval",
    size: "Full",
    brand: "Eskadron",
    color: "blanc",
    condition: "tres-bon-etat",
    price: 35,
    description:
      "Tapis de dressage blanc, taille Full, forme dressage. Utilisé sur trois concours, lavé, pas de tache.",
    images: [img.r],
    discipline: "dressage",
    status: "publiee",
    publishedAt: "2026-09-04T12:00:00Z",
    seller: sellers.ines,
  },
  {
    kind: "listing",
    id: "l7",
    slug: "gilet-protection-enfant-fouganza-12-ans",
    title: "Gilet de protection enfant",
    categorySlug: "casques-protections",
    subCategorySlug: "gilets-protection",
    audience: "cavalier-enfant",
    size: "12 ans",
    brand: "Fouganza",
    color: "noir",
    condition: "bon-etat",
    price: 0,
    description:
      "Gilet de protection niveau 3, taille 12 ans. Donné à qui en a besoin, à récupérer au club le samedi matin. Aucune chute avec.",
    images: [img.e],
    status: "publiee",
    publishedAt: "2026-09-03T19:45:00Z",
    seller: sellers.theo,
  },
  {
    kind: "listing",
    id: "l8",
    slug: "filet-cheval-de-luxe-cob-havane",
    title: "Filet cuir Cheval de Luxe muserolle combinée",
    categorySlug: "briderie",
    subCategorySlug: "bridons",
    audience: "poney",
    size: "Cob",
    brand: "Cheval de Luxe",
    color: "havane",
    condition: "tres-bon-etat",
    price: 55,
    description:
      "Filet en cuir havane, taille Cob, muserolle française combinée, frontal strass. Rênes en caoutchouc incluses. Cuir entretenu régulièrement.",
    images: [img.f, img.g],
    status: "reservee",
    publishedAt: "2026-09-02T14:30:00Z",
    seller: sellers.lucas,
  },
  {
    kind: "listing",
    id: "l9",
    slug: "couverture-exterieur-bucas-135-200g",
    title: "Couverture d'extérieur Bucas Smartex 200 g",
    categorySlug: "couvertures",
    subCategorySlug: "couvertures-exterieur",
    audience: "poney",
    size: "135 cm",
    brand: "Bucas",
    color: "bleu-marine",
    condition: "bon-etat",
    price: 70,
    description:
      "Couverture imperméable 200 g, taille 135 cm (poney D). Lavée et réimperméabilisée cet été. Une petite réparation propre sur le flanc gauche, photo sur demande.",
    images: [img.h],
    status: "publiee",
    publishedAt: "2026-09-01T11:20:00Z",
    seller: sellers.sophie,
  },
  {
    kind: "listing",
    id: "l10",
    slug: "pantalon-pikeur-fond-integral-38",
    title: "Pantalon Pikeur Lucinda Grip fond intégral",
    categorySlug: "pantalons",
    subCategorySlug: "pantalons-fond-integral",
    audience: "cavalier-adulte",
    size: "38",
    brand: "Pikeur",
    color: "beige",
    condition: "neuf-etiquette",
    price: 95,
    description:
      "Pantalon Pikeur beige, taille 38, fond intégral grip. Neuf avec étiquette, erreur de taille à l'achat. Prix neuf 179 €.",
    images: [img.i],
    discipline: "dressage",
    status: "publiee",
    publishedAt: "2026-08-30T09:05:00Z",
    seller: sellers.ines,
  },
  {
    kind: "listing",
    id: "l11",
    slug: "guetres-veredus-carbon-gel-full",
    title: "Guêtres Veredus Carbon Gel Vento",
    categorySlug: "protections",
    subCategorySlug: "guetres",
    audience: "cheval",
    size: "Full",
    brand: "Veredus",
    color: "noir",
    condition: "bon-etat",
    price: 60,
    description:
      "Paire de guêtres antérieures Veredus Carbon Gel Vento, taille Full. Velcros en bon état, coques sans fissure.",
    images: [img.j, img.k],
    discipline: "cso",
    status: "publiee",
    publishedAt: "2026-08-29T17:00:00Z",
    seller: sellers.nathan,
  },
  {
    kind: "listing",
    id: "l12",
    slug: "mini-chaps-tattini-m",
    title: "Mini-chaps cuir Tattini",
    categorySlug: "chaussures-bottes",
    subCategorySlug: "mini-chaps",
    audience: "cavalier-adulte",
    size: "M",
    brand: "Tattini",
    color: "marron",
    condition: "satisfaisant",
    price: 20,
    description:
      "Mini-chaps en cuir marron, taille M. Cuir marqué mais fermetures éclair fonctionnelles. Parfaites pour le quotidien.",
    images: [img.b],
    status: "publiee",
    publishedAt: "2026-08-28T13:15:00Z",
    seller: sellers.chloe,
  },
  {
    kind: "listing",
    id: "l13",
    slug: "selle-poney-kieffer-15",
    title: "Selle poney Kieffer 15\"",
    categorySlug: "selles",
    subCategorySlug: "selles-poney",
    audience: "poney",
    size: '15"',
    brand: "Kieffer",
    color: "noir",
    condition: "bon-etat",
    price: 280,
    description:
      "Selle mixte poney Kieffer 15\", cuir noir, arcade medium. Convient à un poney C ou D. Étriers de sécurité enfant inclus.",
    images: [img.o, img.p],
    discipline: "pony-games",
    status: "publiee",
    publishedAt: "2026-08-27T10:40:00Z",
    seller: sellers.lucas,
  },
  {
    kind: "listing",
    id: "l14",
    slug: "gants-uvex-sportstyle-8",
    title: "Gants Uvex Sportstyle",
    categorySlug: "gants",
    subCategorySlug: "gants-toutes-saisons",
    audience: "cavalier-adulte",
    size: "8",
    brand: "Uvex",
    color: "noir",
    condition: "tres-bon-etat",
    price: 15,
    description: "Gants Uvex Sportstyle taille 8, portés deux fois, trop petits pour moi.",
    images: [img.c],
    status: "publiee",
    publishedAt: "2026-08-26T08:30:00Z",
    seller: sellers.theo,
  },
  {
    kind: "listing",
    id: "l15",
    slug: "veste-concours-equipe-hunter-s",
    title: "Veste de concours Équipe Hunter",
    categorySlug: "tenues-concours",
    subCategorySlug: "tenues-equipe",
    audience: "cavalier-adulte",
    size: "S",
    brand: "Equiline",
    color: "bleu-marine",
    condition: "tres-bon-etat",
    price: 80,
    description:
      "Veste Equiline aux couleurs de l'équipe Hunter, taille S. Portée une saison complète, nettoyée à sec. Boutons du club intacts.",
    images: [img.q, img.x],
    discipline: "hunter",
    team: "hunter",
    status: "publiee",
    publishedAt: "2026-08-25T15:50:00Z",
    seller: sellers.margaux,
  },
  {
    kind: "listing",
    id: "l16",
    slug: "licol-cuir-felix-buhler-full",
    title: "Licol cuir Felix Bühler",
    categorySlug: "licols-longes",
    subCategorySlug: "licols-cuir",
    audience: "cheval",
    size: "Full",
    brand: "Felix Bühler",
    color: "havane",
    condition: "bon-etat",
    price: 25,
    description: "Licol en cuir havane, taille Full, boucleries laiton. Longe assortie offerte.",
    images: [img.d],
    status: "publiee",
    publishedAt: "2026-08-24T12:00:00Z",
    seller: sellers.camille,
  },
  {
    kind: "listing",
    id: "l17",
    slug: "mors-sprenger-double-brisure-12-5",
    title: "Mors Sprenger KK Ultra double brisure",
    categorySlug: "mors",
    subCategorySlug: "mors-double-brisure",
    audience: "cheval",
    size: "12.5 cm",
    brand: "Sprenger",
    color: "gris",
    condition: "tres-bon-etat",
    price: 65,
    description: "Mors Sprenger KK Ultra 12,5 cm, aurigan, anneaux 16 mm. Aucune rayure.",
    images: [img.e],
    discipline: "dressage",
    status: "publiee",
    publishedAt: "2026-08-22T09:15:00Z",
    seller: sellers.ines,
  },
  {
    kind: "listing",
    id: "l18",
    slug: "sac-pansage-equitheme",
    title: "Sac de pansage Equithème garni",
    categorySlug: "soins-pansage",
    subCategorySlug: "coffres-sacs",
    audience: "cheval",
    brand: "Equithème",
    color: "bleu",
    condition: "bon-etat",
    price: 18,
    description:
      "Sac de pansage bleu marine avec étrille, bouchon, brosse douce, cure-pied et peigne à crinière. Idéal pour un premier équipement.",
    images: [img.f],
    status: "publiee",
    publishedAt: "2026-08-20T17:30:00Z",
    seller: sellers.chloe,
  },
  {
    kind: "listing",
    id: "l19",
    slug: "polo-equipe-equifun-m",
    title: "Polo Équipe Equifun",
    categorySlug: "tenues-concours",
    subCategorySlug: "tenues-equipe",
    audience: "cavalier-adulte",
    size: "M",
    brand: "HKM",
    color: "bleu",
    condition: "bon-etat",
    price: 15,
    description: "Polo de l'équipe Equifun, taille M adulte. Bon état général.",
    images: [img.g],
    discipline: "equifun",
    team: "equifun",
    status: "vendue",
    publishedAt: "2026-08-15T10:00:00Z",
    seller: sellers.sophie,
  },
  {
    kind: "listing",
    id: "l20",
    slug: "sangle-courte-kentucky-65",
    title: "Sangle courte anatomique Kentucky 65 cm",
    categorySlug: "selles",
    subCategorySlug: "sangles-courtes",
    audience: "cheval",
    size: "65 cm",
    brand: "Kentucky",
    color: "noir",
    condition: "bon-etat",
    price: 40,
    description: "Sangle courte anatomique mouton synthétique, 65 cm, pour selle de dressage.",
    images: [img.h],
    discipline: "dressage",
    status: "publiee",
    publishedAt: "2026-08-12T14:20:00Z",
    seller: sellers.ines,
  },
  {
    kind: "listing",
    id: "l21",
    slug: "boots-cavallo-38",
    title: "Boots Cavallo Linus Jump",
    categorySlug: "chaussures-bottes",
    subCategorySlug: "boots-equitation",
    audience: "cavalier-adulte",
    size: "38",
    brand: "Cavallo",
    color: "marron",
    condition: "bon-etat",
    price: 55,
    description: "Boots en cuir marron Cavallo, pointure 38, fermeture éclair arrière. Semelles en bon état.",
    images: [img.i],
    status: "publiee",
    publishedAt: "2026-08-10T09:30:00Z",
    seller: sellers.margaux,
  },
  {
    kind: "listing",
    id: "l22",
    slug: "bonnet-anti-mouches-poney-bleu",
    title: "Bonnet anti-mouches poney",
    categorySlug: "anti-mouches",
    subCategorySlug: "bonnets-anti-mouches",
    audience: "poney",
    size: "Poney",
    brand: "Waldhausen",
    color: "bleu-marine",
    condition: "tres-bon-etat",
    price: 8,
    description: "Bonnet anti-mouches taille poney, bleu marine, oreilles en filet. Une saison.",
    images: [img.j],
    status: "publiee",
    publishedAt: "2026-08-08T11:00:00Z",
    seller: sellers.lucas,
  },
  {
    kind: "listing",
    id: "l23",
    slug: "casque-uvex-exxential-enfant-52",
    title: "Casque Uvex Exxential II enfant",
    categorySlug: "casques-protections",
    subCategorySlug: "casques",
    audience: "cavalier-enfant",
    size: "52 cm",
    brand: "Uvex",
    color: "bleu",
    condition: "bon-etat",
    price: 30,
    description:
      "Casque Uvex réglable 51-55 cm, bleu mat. Aucune chute, acheté en 2025. Un casque d'occasion doit être inspecté avant usage.",
    images: [img.k],
    status: "publiee",
    publishedAt: "2026-08-05T16:45:00Z",
    seller: sellers.theo,
  },
  {
    kind: "listing",
    id: "l24",
    slug: "tapis-equipe-dressage-full",
    title: "Tapis de selle Équipe Dressage",
    categorySlug: "tapis-pads",
    subCategorySlug: "tapis-selle",
    audience: "cheval",
    size: "Full",
    brand: "Equithème",
    color: "bleu-marine",
    condition: "bon-etat",
    price: 25,
    description: "Tapis aux couleurs de l'équipe Dressage, taille Full, forme dressage. Logo brodé.",
    images: [img.r, img.v],
    discipline: "dressage",
    team: "dressage",
    status: "publiee",
    publishedAt: "2026-08-02T10:10:00Z",
    seller: sellers.ines,
  },
];

export const PRODUCTS: Product[] = [
  {
    kind: "product",
    id: "p1",
    slug: "polo-club-bayard",
    name: "Polo Club Bayard",
    category: "textile",
    description:
      "Le polo officiel du club, en piqué de coton bleu marine, logo brodé sur le cœur. Coupe unisexe.",
    images: [img.x, img.l],
    price: 32,
    variants: [
      { id: "p1-xs", label: "XS", stock: 2 },
      { id: "p1-s", label: "S", stock: 5 },
      { id: "p1-m", label: "M", stock: 0 },
      { id: "p1-l", label: "L", stock: 4 },
      { id: "p1-xl", label: "XL", stock: 3 },
    ],
    published: true,
    createdAt: "2026-06-01T00:00:00Z",
    sizeNote: "Taille normalement. Entre deux tailles, prenez la taille au-dessus.",
  },
  {
    kind: "product",
    id: "p2",
    slug: "sweat-capuche-club-bayard",
    name: "Sweat à capuche Club Bayard",
    category: "textile",
    description:
      "Sweat à capuche molletonné, logo Club Bayard imprimé sur la poitrine et « Équitation Paris » dans le dos.",
    images: [img.w, img.v],
    price: 45,
    variants: [
      { id: "p2-8", label: "8 ans", stock: 3 },
      { id: "p2-10", label: "10 ans", stock: 4 },
      { id: "p2-12", label: "12 ans", stock: 2 },
      { id: "p2-s", label: "S", stock: 6 },
      { id: "p2-m", label: "M", stock: 5 },
      { id: "p2-l", label: "L", stock: 1 },
    ],
    published: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    kind: "product",
    id: "p3",
    slug: "casquette-club-bayard",
    name: "Casquette Club Bayard",
    category: "accessoires-cavalier",
    description: "Casquette bleu marine brodée, réglable. Taille unique.",
    images: [img.a],
    price: 18,
    variants: [{ id: "p3-u", label: "Taille unique", stock: 12 }],
    published: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    kind: "product",
    id: "p4",
    slug: "tapis-selle-club-bayard",
    name: "Tapis de selle Club Bayard",
    category: "accessoires-cheval",
    description:
      "Tapis de selle mixte bleu marine, liseré blanc, logo brodé sur les deux côtés. Fabriqué par Equithème.",
    images: [img.r, img.s],
    price: 39,
    variants: [
      { id: "p4-poney", label: "Poney", stock: 3 },
      { id: "p4-cob", label: "Cob", stock: 2 },
      { id: "p4-full", label: "Full", stock: 4 },
    ],
    published: true,
    createdAt: "2026-06-15T00:00:00Z",
  },
  {
    kind: "product",
    id: "p5",
    slug: "veste-concours-equipe-cce",
    name: "Veste de concours Équipe CCE",
    category: "tenue-equipe",
    description:
      "Veste de concours officielle de l'équipe CCE, bleu marine, passepoil bleu ciel et écusson du club. Sur commande : précommande jusqu'au 15 octobre, livraison au club début décembre.",
    images: [img.l, img.m],
    price: 149,
    variants: [
      { id: "p5-xs", label: "XS", stock: 0, onOrder: true, leadTime: "6 à 8 semaines" },
      { id: "p5-s", label: "S", stock: 0, onOrder: true, leadTime: "6 à 8 semaines" },
      { id: "p5-m", label: "M", stock: 0, onOrder: true, leadTime: "6 à 8 semaines" },
      { id: "p5-l", label: "L", stock: 0, onOrder: true, leadTime: "6 à 8 semaines" },
    ],
    team: "cce",
    teamOnly: true,
    published: true,
    createdAt: "2026-08-20T00:00:00Z",
    sizeNote: "Essayage possible au secrétariat le samedi matin avant de précommander.",
  },
  {
    kind: "product",
    id: "p6",
    slug: "polo-equipe-pony-games",
    name: "Polo Équipe Pony-Games",
    category: "tenue-equipe",
    description: "Polo bleu ciel de l'équipe Pony-Games, logo brodé, nom du cavalier possible au dos.",
    images: [img.n, img.o],
    price: 28,
    variants: [
      { id: "p6-6", label: "6 ans", stock: 2 },
      { id: "p6-8", label: "8 ans", stock: 4 },
      { id: "p6-10", label: "10 ans", stock: 5 },
      { id: "p6-12", label: "12 ans", stock: 3 },
      { id: "p6-14", label: "14 ans", stock: 1 },
      { id: "p6-s", label: "S", stock: 2 },
      { id: "p6-m", label: "M", stock: 2 },
    ],
    team: "pony-games",
    teamOnly: true,
    published: true,
    createdAt: "2026-07-10T00:00:00Z",
  },
  {
    kind: "product",
    id: "p7",
    slug: "tour-de-cou-club-bayard",
    name: "Tour de cou polaire Club Bayard",
    category: "accessoires-cavalier",
    description: "Tour de cou polaire bleu marine, logo brodé. Indispensable pour les reprises d'hiver.",
    images: [img.b],
    price: 12,
    variants: [{ id: "p7-u", label: "Taille unique", stock: 20 }],
    published: true,
    createdAt: "2026-07-10T00:00:00Z",
  },
  {
    kind: "product",
    id: "p8",
    slug: "gourde-club-bayard",
    name: "Gourde isotherme Club Bayard",
    category: "divers",
    description: "Gourde inox 500 ml, double paroi, gravure Club Bayard.",
    images: [img.c],
    price: 22,
    variants: [
      { id: "p8-marine", label: "Bleu marine", stock: 8 },
      { id: "p8-blanc", label: "Blanc", stock: 0 },
    ],
    published: true,
    createdAt: "2026-07-10T00:00:00Z",
  },
  {
    kind: "product",
    id: "p9",
    slug: "polo-equipe-hunter",
    name: "Polo Équipe Hunter",
    category: "tenue-equipe",
    description: "Polo bleu marine de l'équipe Hunter, logo brodé sur la manche.",
    images: [img.q],
    price: 28,
    variants: [
      { id: "p9-s", label: "S", stock: 3 },
      { id: "p9-m", label: "M", stock: 3 },
      { id: "p9-l", label: "L", stock: 2 },
    ],
    team: "hunter",
    teamOnly: false,
    published: true,
    createdAt: "2026-07-10T00:00:00Z",
  },
  {
    kind: "product",
    id: "p10",
    slug: "bonnet-club-bayard",
    name: "Bonnet tricot Club Bayard",
    category: "accessoires-cavalier",
    description: "Bonnet en maille bleu marine avec pompon blanc, écusson tissé.",
    images: [img.d],
    price: 15,
    variants: [{ id: "p10-u", label: "Taille unique", stock: 10 }],
    published: true,
    createdAt: "2026-08-01T00:00:00Z",
  },
  {
    kind: "product",
    id: "p11",
    slug: "sac-pansage-club-bayard",
    name: "Sac de pansage Club Bayard",
    category: "accessoires-cheval",
    description: "Sac de pansage bleu marine à compartiments, logo brodé. Livré vide.",
    images: [img.f],
    price: 29,
    variants: [{ id: "p11-u", label: "Taille unique", stock: 4 }],
    published: true,
    createdAt: "2026-08-01T00:00:00Z",
  },
  {
    kind: "product",
    id: "p12",
    slug: "veste-softshell-equipe-dressage",
    name: "Veste softshell Équipe Dressage",
    category: "tenue-equipe",
    description: "Veste softshell bleu marine, liseré blanc, brodée « Équipe Dressage ».",
    images: [img.r],
    price: 69,
    variants: [
      { id: "p12-s", label: "S", stock: 1 },
      { id: "p12-m", label: "M", stock: 2 },
      { id: "p12-l", label: "L", stock: 0 },
    ],
    team: "dressage",
    teamOnly: false,
    published: true,
    createdAt: "2026-08-15T00:00:00Z",
  },
];
